### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by 1637619627qq** [antinucleus/Hackintosh#1]
Thank you for your volume patch. I have driven my earphone hole. I have another problem. The brightness of your Hackintosh can be adjusted, but mine cannot

**Comment by antinucleus** [comment]
You are welcome. I didn't have any problem with the screen brightness. I have couldn't set up the trackpad driver only. All of the other hardwares  have worked well with this hackintosh setup.

**Comment by antinucleus** [comment]
Closes #1
